### ISSUE TITLE
Flaw with tiller limiter

### ISSUE THREAD

**Issue by GoogleWasAllMyIdea** [Ariakim-Taiyo/777-Realism-Overhaul#4]
When in the air at 140 knots the rudder becomes ineffective due to the limiter I crashed because it would not move.

**Comment by Ariakim-Taiyo** [comment]
The tiller and rudder system are only semi-linked. The rudder reacts to a FBW output made from a yaw input, and has no relation to the tiller restriction. It is most likely that the rudder simply takes too long to respond to inputs for your specific use case.

**Comment by GoogleWasAllMyIdea** [comment]
oh okay then.
